var stations = [
	// Bronx
    { loc: "674,978,24", name: "Van Condlandt/ 242 st.", imgName: ["/last_stop/Bronx/242_street_van_courtland_park_1.jpg"]},
    { loc: "912,986,22", name: "Woodlawn", imgName: ["/last_stop/Bronx/woodlawn_4.jpg"]},
    { loc: "1064,828,24", name: "Wakefield/ 241 st. ", imgName: ["/last_stop/Bronx/241_street_wakefield_2-2.jpg", "/last_stop/Bronx/241_street_wakefield_2.jpg"]},
    { loc: "1065,874,17", name: "Nereid Av", imgName: [ "/last_stop/Bronx/nereid_avenue_2_5.jpg", "/last_stop/Bronx/nereid_avenue_2_5-2.jpg"]},
    { loc: "1061,904,15", name: "233 st", imgName: [ "/last_stop/Bronx/233_street_2_5.jpg", "/last_stop/Bronx/233_street_2_5-2.jpg"]},
    { loc: "1059,945,15", name: "225 st", imgName: [ "/last_stop/Bronx/225_street_2_5.jpg"]},
    { loc: "1068,982,15", name: "219 st", imgName: [ "/last_stop/Bronx/219_street_2_5.jpg", "/last_stop/Bronx/219_street_2_5-2.jpg"]},
    { loc: "1081,1022,15", name: "225 st", imgName: [ "/last_stop/Bronx/225_street_2_5.jpg"]},
    { loc: "1113,1076,15", name: "Burke Av", imgName: [ "/last_stop/Bronx/burke_avenue_2_5-2.jpg", "/last_stop/Bronx/burke_avenue_2_5.jpg"]},
    { loc: "1140,1113,15", name: "Allerton Av", imgName: [ "/last_stop/Bronx/allerton_avenue_2_5.jpg", "/last_stop/Bronx/allerton_avenue_2_5-2.jpg"]},
    { loc: "1163,1157,15", name: "Pelham Pkwy", imgName: [ "/last_stop/Bronx/pelham_parkway_2_5-3.jpg", "/last_stop/Bronx/pelham_parkway_2_5.jpg"]},
    { loc: "1164,1210,15", name: "Bronx Park East", imgName: [ "/last_stop/Bronx/bronx_park_east_2_5.jpg"]},
    { loc: "1157,1270,15", name: "E 180 st", imgName: [ "/last_stop/Bronx/east_180_street_2_5.jpg"]},
    { loc: "908,1040,15", name: "Mosholu Pkwy", imgName: [ "/last_stop/Bronx/mosholu_parkway_4.jpg"]},
    { loc: "993,1037,15", name: "Norwood/ 205 st", imgName: [ "/last_stop/Bronx/205_street_d.jpg", "/last_stop/Bronx/205_street_d-2.jpg"]},
    { loc: "934,1092,15", name: "Bedford PK Blvd", imgName: [ "/last_stop/Bronx/bedford_park_bolevard_b_d-2.jpg", "/last_stop/Bronx/bedford_park_boulevard_4.jpg", "/last_stop/Bronx/bedford_park_boulevard_b_d.jpg"]},
    { loc: "897,1109,15", name: "Beford Pk Blvd / Lehman College", imgName: [ "/last_stop/Bronx/"]},
    { loc: "688,1050,15", name: "238 st", imgName: [ "/last_stop/Bronx/238_street_1.jpg"]},
    { loc: "684,1088,15", name: "231 st", imgName: [ "/last_stop/Bronx/231_street_1.jpg", "/last_stop/Bronx/ 231_street_1-2.jpg"]},
    { loc: "669,1127,15", name: "Marble Hill/ 225 st", imgName: [ "/last_stop/Bronx/225_street_1.jpg", "/last_stop/Bronx/225_street_1-2.jpg"]},
    { loc: "896,1153,15", name: "Kingsbridge Rd", imgName: [ "/last_stop/Bronx/kingsbridge_road_b_d-2.jpg", "/last_stop/Bronx/Bronx/kingsbridge_road_b_d-3.jpg", "/last_stop/Bronx/kingsbridge_road_b_d.jpg"]},
    { loc: "927,1147,15", name: "Kingsbridge Rd", imgName: [ "/last_stop/Bronx/kingsbridge_road_4.jpg"]},
    { loc: "923,1204,15", name: "Fordham Rd", imgName: [ "/last_stop/Bronx/fordham_road_4.jpg", "/last_stop/Bronx/fordham_road_b_d-2.jpg", "/last_stop/Bronx/fordham_road_b_d.jpg"]},
    { loc: "1217,873,15", name: "Eastchester/ Dyre Av", imgName: [ "/last_stop/Bronx/dyre_avenue_5.jpg"]},
    { loc: "1216,913,15", name: "Baychester Av", imgName: [ "/last_stop/Bronx/ baychester_avenue_5.jpg"]},
    { loc: "1209,1017,15", name: "Gun Hill Rd", imgName: [ "/last_stop/Bronx/gun_hill_road_2_5.jpg", "/last_stop/Bronx/gun_hill_road_5.jpg"]},
    { loc: "1209,1124,15", name: "Pelham Pkwy", imgName: [ "/last_stop/Bronx/pelham_parkway_5.jpg"]},
    { loc: "1205,1170,15", name: "Morris park", imgName: [ "/last_stop/Bronx/morris_park_5-2.jpg", "/last_stop/Bronx/morris_park_5.jpg"]},
    { loc: "884,1215,15", name: "Fordham Rd", imgName: [ "/last_stop/Bronx/fordham_road_b_d.jpg", "/last_stop/Bronx/fordham_road_b_d-2.jpg", "/last_stop/Bronx/fordham_road_4.jpg	"]},
    { loc: "881,1246,15", name: "183 st", imgName: [ "/last_stop/Bronx/183_street_4-2.jpg", "/last_stop/Bronx/183_street_4-3.jpg"]},
    { loc: "923,1245,15", name: "182-183 Sts", imgName: [ "/last_stop/Bronx/182-283_streets_b_d.jpg"]},
    { loc: "884,1274,15", name: "Burnside Av", imgName: [ "/last_stop/Bronx/burnside_avenue_4-3.jpg", "/last_stop/Bronx/burnside_avenue_4-2.jpg", "/last_stop/Bronx/burnside_avenue_4-4.jpg", "/last_stop/Bronx/burnside_avenue_4.jpg"]},
    { loc: "922,1292,15", name: "Tremont Av", imgName: [ "/last_stop/Bronx/tremont_avenue_b_d.jpg"]},
    { loc: "881,1308,15", name: "176 St ", imgName: [ "/last_stop/Bronx/176_street_4.jpg", "/last_stop/Bronx/176_street_4b.jpg"]},
    { loc: "923,1330,15", name: "174-175 Sts", imgName: [ "/last_stop/Bronx/174-175_streets_b_d.jpg"]},
    { loc: "1111,1304,15", name: "West Farms Sq/ E Tremont Av", imgName: [ "/last_stop/Bronx/west_farms_square_east_tremont_avenue_2_5-2.jpg", "/last_stop/Bronx/west_farms_square_east_tremont_avenue_2_5.jpg"]},
    { loc: "1122,1345,15", name: "174 st", imgName: [ "/last_stop/Bronx/174_street_2_5.jpg", "/last_stop/Bronx/174_street_2_5-2.jpg"]},
    { loc: "1426,1060,15", name: "Pelham Bay Park", imgName: [ "/last_stop/Bronx/pelham_bay_park_6-2.jpg", "/last_stop/Bronx/pelham_bay_park_6-3.jpg", "/last_stop/Bronx/pelham_bay_park_6.jpg"]},
    { loc: "1423,1103,15", name: "Buhre Av", imgName: [ "/last_stop/Bronx/buhre_avenue_6.jpg"]},
    { loc: "1416,1148,15", name: "Middletown Rd", imgName: [ "/last_stop/Bronx/middletown_road_6.jpg"]},
    { loc: "1389,1202,15", name: "Weschester sq/ East Tremont Av", imgName: [ "/last_stop/Bronx/westchester_square_east_tremont_avenue_6.jpg"]},
    { loc: "1351,1245,15", name: "Zerega Av", imgName: [ "/last_stop/Bronx/zerega_avenue_6.jpg"]},
    { loc: "1325,1272,15", name: "Castle Hill Av", imgName: [ "/last_stop/Bronx/castle_hill_avenue_6.jpg"]},
    { loc: "1295,1301,15", name: "Parkchester", imgName: [ "/last_stop/Bronx/parkchester_6.jpg"]},
    { loc: "1260,1335,15", name: "St Lawrence Av", imgName: [ "/last_stop/Bronx/saint_lawrence_avenue_6.jpg"]},
    { loc: "1218,1371,15", name: "Morrison Av/ Soundview", imgName: [ "/last_stop/Bronx/morrison_avenue_sound_view_6.jpg"]},
    { loc: "1187,1400,15", name: "Elder Av", imgName: [ "/last_stop/Bronx/elder_avenue_6.jpg"]},
    { loc: "1128,1402,15", name: "Freeman St", imgName: [ "/last_stop/Bronx/freeman_street_2_5-2.jpg", "/last_stop/Bronx/freeman_street_2_5.jpg"]},
    { loc: "1177,1431,15", name: "Whitlock Av", imgName: [ "/last_stop/Bronx/whitlock_avenue_6.jpg"]},
    { loc: "927,1390,15", name: "170 St", imgName: [ "/last_stop/Bronx/170_street_4.jpg"]},
    { loc: "887,1390,15", name: "170 St", imgName: [ "/last_stop/Bronx/170_street_b_d.jpg", "/last_stop/Bronx/170_street_b_d-2.jpg"]},
    { loc: "1125,1453,15", name: "Simpson St", imgName: [ "/last_stop/Bronx/simpson_street_2_5.jpg"]},
    { loc: "1165,1483,15", name: "Hunts Point Av", imgName: [ "/last_stop/Bronx/hunts_point_avenue_6-2.jpg", "/last_stop/Bronx/hunts_point_avenue_6.jpg"]},
    { loc: "923,1436,15", name: "167 St", imgName: [ "/last_stop/Bronx/167_street_4.jpg"]},
    { loc: "886,1440,15", name: "167 St", imgName: [ "/last_stop/Bronx/167_street_b_d.jpg", "/last_stop/Bronx/167_street_b_d-2.jpg"]},
    { loc: "1117,1495,15", name: "Intervale Av", imgName: [ "/last_stop/Bronx/intervale_avenue_2_5.jpg"]},
    { loc: "1152,1522,15", name: "Longwood Av", imgName: [ "/last_stop/Bronx/longwood_avenue_6-2.jpg", "/last_stop/Bronx/longwood_avenue_6.jpg"]},
    { loc: "1094,1522,15", name: "Prospect Av", imgName: [ "/last_stop/Bronx/prospect_avenue_2_5.jpg"]},
    { loc: "1143,1564,15", name: "E 149 St", imgName: [ "/last_stop/Bronx/east_149_street_6-2.jpg", "/last_stop/Bronx/east_149_street_6.jpg"]},
    { loc: "1056,1552,15", name: "Jackson Av", imgName: [ "/last_stop/Bronx/jackson_avenue_2_5.jpg"]},
    { loc: "1137,1599,15", name: "143 St/ St. Mary&apos;s St", imgName: [ "/last_stop/Bronx/east_143_street_6.jpg"]},
    { loc: "896,1509,15", name: "161 st./ Yankee Stadium", imgName: [ "/last_stop/Bronx/161_street_yankee_stadium_b_d_4-2.jpg", "/last_stop/Bronx/161_street_yankee_stadium_b_d_4.jpg"]},
	{ loc: "904,1557,15", name: "149 St- Grand Concourse", imgName: [ "/last_stop/Bronx/"]},
    { loc: "935,1583,15", name: "149 St- Grand Concourse", imgName: [ "/last_stop/Bronx/149_street_grand_concourse_2_4_5.jpg"]},	
    { loc: "970,1576,15", name: "3 Av-149 St", imgName: [ "/last_stop/Bronx/3_avenue_149_street_2_5.jpg"]},
    { loc: "1095,1634,15", name: "Cypress Av", imgName: [ "/last_stop/Bronx/cypress_avenue_6.jpg"]},
    { loc: "1036,1642,15", name: "Brook Av", imgName: [ "/last_stop/Bronx/brook_avenue_6.jpg"]},
    { loc: "951,1650,15", name: "3 Av/ 138 St", imgName: [ "/last_stop/Bronx/3_avenue_138_street_6-2.jpg", "/last_stop/Bronx/3_avenue_138_street_6.jpg"]},
    { loc: "914,1630,15", name: "138 St- Grand Concourse", imgName: [ "/last_stop/Bronx/138_street_4_5.jpg", "/last_stop/Bronx/138_street_4_5-2.jpg"]},
    { loc: "886,1356,15", name: "Elder Av", imgName: [ "/last_stop/Bronx/elder_avenue_6.jpg"]},
    { loc: "883,1355,13", name: "Mt Eden Av", imgName: [ "/last_stop/Bronx/no_name_stop-1.jpg", "/last_stop/Bronx/mount_eden_avenue_4.jpg"]},
	// Manhattan
    { loc: "568,1198,19", name: "215 st", line: ["1"], imgName: ["/last_stop/Manhattan/215_street_1.jpg", "/last_stop/Manhattan/215_street_1-3.jpg" ]},
    { loc: "522,1244,15", name: "Inwood/ 207 st", line: ["A"], imgName: ["/last_stop/Manhattan/inwood_207_street_a.jpg", "/last_stop/Manhattan/inwood_207_street_a.jpg-2" ]},
    { loc: "553,1248,15", name: "207 st", line: ["1"], imgName: ["/last_stop/Manhattan/207_street_1-2.jpg", "/last_stop/Manhattan/207_street_1.jpg"]},
    { loc: "528,1288,15", name: "Dyckman St", imgName: ["/last_stop/Manhattan/dyckman_street_1-2.jpg" ]},
    { loc: "486,1287,15", name: "Dyckman St", imgName: ["/last_stop/Manhattan/dyckman_street_a.jpg" ]},
    { loc: "517,1321,15", name: "191 st", line: ["1"], imgName: ["/last_stop/Manhattan/191_street_1-2.jpg", "/last_stop/Manhattan/191_street_1-3.jpg", "/last_stop/Manhattan/191_street_1.jpg"]},
    { loc: "464,1328,15", name: "190 St", imgName: ["/last_stop/Manhattan/190_street_a-3.jpg", "/last_stop/Manhattan/190_street_a-2.jpg", "/last_stop/Manhattan/190_street_a.jpg" ]},
    { loc: "512,1364,15", name: "181 St", imgName: ["/last_stop/Manhattan/181_street_a.jpg", "/last_stop/Manhattan/181_street_1-2.jpg" ]},
    { loc: "463,1370,15", name: "181 St", imgName: ["/last_stop/Manhattan/181_street_1.jpg" ]},
    { loc: "476,1416,15", name: "175 St", imgName: ["/last_stop/Manhattan/175_street_a.jpg" ]},
    { loc: "509,1462,15", name: "168 St", imgName: ["/last_stop/Manhattan/168_street_a_c_1.jpg", "/last_stop/Manhattan/168_street_a_c_1-2.jpg" ]},
    { loc: "542,1499,15", name: "163 st./ Amsterdam Av", imgName: ["/last_stop/Manhattan/163_street_c-2.jpg", "/last_stop/Manhattan/163_street_c-3.jpg", "/last_stop/Manhattan/163_street_c.jpg" ]},
    { loc: "571,1537,15", name: "155 St", imgName: ["/last_stop/Manhattan/155_street_c.jpg" ]},
    { loc: "627,1544,15", name: "155 St", imgName: ["/last_stop/Manhattan/155_street_b_d-2.jpg" ]},
    { loc: "509,1549,15", name: "157 St", imgName: ["/last_stop/Manhattan/157-street_1-2.jpg", "/last_stop/Manhattan/157-street_1.jpg" ]},
    { loc: "705,1585,15", name: "Harlem/ 148 St", imgName: ["/last_stop/Manhattan/148_street_lennox_terminal_3.jpg" ]},
    { loc: "587,1610,15", name: "145 St", imgName: ["/last_stop/Manhattan/145_street_a_c_b_d.jpg", "/last_stop/Manhattan/145_street_a_c_b_d.jpg-3", "145_street_a_c_b_d.jpg-2" ]},
    { loc: "510,1612,15", name: "145 St", imgName: ["/last_stop/Manhattan/145_street_1-2.jpg" ]},
    { loc: "757,1620,15", name: "145 St", imgName: ["/last_stop/Manhattan/145_street_3.jpg" ]},
    { loc: "766,1671,15", name: "135 St", imgName: ["/last_stop/Manhattan/135_street_2_3.jpg" ]},
    { loc: "587,1668,15", name: "135 St", imgName: ["/last_stop/Manhattan/135_street_b_c-2.jpg", "/last_stop/Manhattan/135_street_b_c.jpg" ]},
    { loc: "514,1659,15", name: "137 St/ City College", imgName: ["/last_stop/Manhattan/137_street_city_college_1-3.jpg", "/last_stop/Manhattan/137_street_city_college_1.jpg" ]},
    { loc: "904,1703,22", name: "125 St", imgName: ["/last_stop/Manhattan/125_street_4_5_6-2.jpg", "/last_stop/Manhattan/125_street_4_5_6.jpg" ]},
    { loc: "758,1714,19", name: "125 St", imgName: ["/last_stop/Manhattan/125_street_2_3.jpg", "/last_stop/Manhattan/125_street_2_3-2.jpg" ]},
    { loc: "588,1711,18", name: "125 St", imgName: ["/last_stop/Manhattan/125_street_a_c_b_d-3.jpg", "125_street_a_c_b_d-2.jpg", "/last_stop/Manhattan/125_street_a_c_b_d.jpg" ]},
    { loc: "515,1700,18", name: "125 St", imgName: ["/last_stop/Manhattan/125_street_1.jpg" ]},
    { loc: "904,1749,18", name: "116 St", imgName: ["/last_stop/Manhattan/116_street_6-2.jpg", "/last_stop/Manhattan/116_street_6.jpg" ]},
    { loc: "763,1754,18", name: "116 St", imgName: ["/last_stop/Manhattan/116_street_2_3-2.jpg", "/last_stop/Manhattan/116_street_2_3.jpg" ]},
    { loc: "593,1752,18", name: "116 St", imgName: ["/last_stop/Manhattan/116_street_b_c.jpg" ]},
    { loc: "512,1743,18", name: "116 St/ Columbia University", imgName: ["/last_stop/Manhattan/116_street_columbia_university_1.jpg" ]},
    { loc: "897,1787,18", name: "110 St", imgName: ["/last_stop/Manhattan/110_street_6.jpg" ]},
    { loc: "757,1789,18", name: "Central Park North/ 110 St", imgName: ["/last_stop/Manhattan/110_street_central_park_north_2_3.jpg" ]},
    { loc: "590,1794,18", name: "Cathedral Pkwy/ 110 St", imgName: ["/last_stop/Manhattan/110_street_cathedral_parkway_b_c.jpg" ]},
    { loc: "521,1791,18", name: "Cathedral Pkwy/ 110 St", imgName: ["/last_stop/Manhattan/cathedral_parkway_110_street_1.jpg" ]},
    { loc: "908,1854,18", name: "103 St", imgName: ["/last_stop/Manhattan/103_street_6-2.jpg", "/last_stop/Manhattan/103_street_6.jpg" ]},
    { loc: "588,1845,18", name: "103 St", imgName: ["/last_stop/Manhattan/103_street_b_c.jpg" ]},
    { loc: "524,1849,18", name: "103 St", imgName: ["/last_stop/Manhattan/103_street_1.jpg" ]},
    { loc: "900,1897,18", name: "96 St", imgName: ["/last_stop/Manhattan/96_street_6.jpg" ]},
    { loc: "585,1902,18", name: "96 St", imgName: ["/last_stop/Manhattan/96_street_b_c.jpg" ]},
    { loc: "525,1899,18", name: "96 St", imgName: ["/last_stop/Manhattan/96_street_1_2_3.jpg" ]},
    { loc: "899,1947,18", name: "86 St", imgName: ["/last_stop/Manhattan/86_street_4_5_6.jpg" ]},
    { loc: "590,1949,18", name: "86 St", imgName: ["/last_stop/Manhattan/86_street_b_c.jpg" ]},
    { loc: "527,1954,18", name: "86 St", imgName: ["/last_stop/Manhattan/86_street_1-3.jpg", "/last_stop/Manhattan/86_street_1.jpg", "/last_stop/Manhattan/86_street_1-4.jpg", "/last_stop/Manhattan/86_street_1-2.jpg" ]},
    { loc: "900,2018,18", name: "77 St", imgName: ["/last_stop/Manhattan/77_street_6.jpg" ]},
    { loc: "584,1994,18", name: "81 St/ Museum of Natural History", imgName: ["/last_stop/Manhattan/81_street_museum_of_natural_history_b_c-2.jpg", "/last_stop/Manhattan/81_street_museum_of_natural_history_b_c-3.jpg", "/last_stop/Manhattan/81_street_museum_of_natural_history_b_c.jpg" ]},
    { loc: "524,2000,18", name: "79 St", imgName: ["/last_stop/Manhattan/79_street_1.jpg" ]},
    { loc: "589,2041,18", name: "72 St", imgName: ["/last_stop/Manhattan/72_street_b_c.jpg" ]},
    { loc: "531,2045,18", name: "72 St", imgName: ["/last_stop/Manhattan/72_street_1_2_3.jpg" ]},
    { loc: "898,2083,18", name: "68 St/ Hunter College", imgName: ["/last_stop/Manhattan/68_street_6.jpg" ]},
    { loc: "542,2092,18", name: "66 St/ Lincoln Center", imgName: ["/last_stop/Manhattan/66_street_lincoln_center_1.jpg" ]},
    { loc: "578,2156,18", name: "59 St/ Colubus Circle", imgName: ["/last_stop/Manhattan/59_street_colombus_circle_1_a_c_b_d.jpg", "/last_stop/Manhattan/59_street_colombus_circle_1_a_c_b_d-2.jpg" ]},
    { loc: "684,2169,18", name: "57 St/ 7 Av", imgName: ["/last_stop/Manhattan/57_street_n_q_r.jpg" ]},
    { loc: "780,2187,18", name: "57 St", imgName: ["/last_stop/Manhattan/57_street_f-3.jpg", "/last_stop/Manhattan/57_street_f-2.jpg", "/last_stop/Manhattan/57_street_f.jpg" ]},
    { loc: "862,2166,18", name: "5Av/ 59 St", imgName: ["/last_stop/Manhattan/5_avenue_59_street_n_q_r-2.jpg", "/last_stop/Manhattan/5_avenue_59_street_n_q_r.jpg" ]},
    { loc: "892,2118,18", name: "Lexington Av/ 63 St", imgName: ["/last_stop/Manhattan/lexington_avenue_63_street_f.jpg" ]},
    { loc: "925,2155,18", name: "Lexington Av/ 59 St", imgName: ["/last_stop/Manhattan/lexington_avenue_59_street_n_q_r_4_5_6.jpg", "/last_stop/Manhattan/lexington_avenue_59_street_n_q_r_4_5_6-2.jpg" ]},
    { loc: "894,2176,14", name: "59 St", imgName: ["/last_stop/Manhattan/59_street_4_5_6_n_q_r.jpg", "/last_stop/Manhattan/59_street_4_5_6_n_q_r-2.jpg" ]},
    { loc: "1045,2110,18", name: "Roosevelt Island", imgName: ["/last_stop/Manhattan/roosevelt_island_f.jpg" ]},
    { loc: "676,2206,18", name: "7 Av", imgName: ["/last_stop/Manhattan/7_avenue_b_d_e.jpg" ]},
    { loc: "838,2215,20", name: "5 Av/ 53 St", imgName: ["/last_stop/Manhattan/5_avenue_53_street_e_m.jpg" ]},
    { loc: "920,2209,14", name: "51 St", imgName: ["/last_stop/Manhattan/lexington_avenue_53_street_e_m_6-2.jpg", "/last_stop/Manhattan/lexington_avenue_53_street_e_m_6-3.jpg", "/last_stop/Manhattan/lexington_avenue_53_street_e_m_6.jpg" ]},
    { loc: "897,2232,14", name: "51 St", imgName: ["/last_stop/Manhattan/51_street_6_e_m-4.jpg", "/last_stop/Manhattan/51_street_6_e_m-5.jpg", "/last_stop/Manhattan/51_street_6_e_m-2.jpg", "/last_stop/Manhattan/51_street_6_e_m.jpg" ]},
    { loc: "582,2230,18", name: "50 St", imgName: ["/last_stop/Manhattan/50_street_c_e.jpg", "/last_stop/Manhattan/50_street_c_e.jpg-2" ]},
    { loc: "646,2230,18", name: "50 St", imgName: ["/last_stop/Manhattan/50_street_1.jpg" ]},
    { loc: "687,2240,18", name: "49 St", imgName: ["/last_stop/Manhattan/49_street_n_q_r.jpg" ]},
    { loc: "768,2248,18", name: "47-50 Sts/ Rockefeller Ctr", imgName: ["/last_stop/Manhattan/47-50_streets_rockerfeller_center_b_d_f_m.jpg", "/last_stop/Manhattan/47-50_streets_rockerfeller_center_b_d_f_m-2.jpg" ]},
    { loc: "688,2279,18", name: "Times Sq-42 St", imgName: ["/last_stop/Manhattan/times_square_42_street_n_q_r_s_1_2_3_7-1.jpg" ]},
    { loc: "767,2288,18", name: "42 St Bryant Pk", imgName: ["/last_stop/Manhattan/42_street_bryant_park_b_d_f_m_7.jpg" ]},
    { loc: "842,2292,18", name: "5 Av", imgName: ["/last_stop/Manhattan/5_avenue_bryant_park_7_b_d_f_m-2.jpg" ]},
    { loc: "583,2286,18", name: "42 St/ Port Authority Bus Terminal", imgName: ["/last_stop/Manhattan/42_street_port_authority_bus_terminal_a_c_e-2.jpg", "/last_stop/Manhattan/42_street_port_authority_bus_terminal_a_c_e.jpg" ]},
    { loc: "896,2286,18", name: "Grand Central/ 42 St", imgName: ["/last_stop/Manhattan/42_street_grand_centeral_4_5_6_7_s.jpg", "/last_stop/Manhattan/42_street_grand_centeral_4_5_6_7_s-2.jpg", "/last_stop/Manhattan/42_street_grand_centeral_4_5_6_7_s-3.jpg" ]},
    { loc: "880,2336,18", name: "33 St", imgName: ["/last_stop/Manhattan/33_street_6.jpg" ]},
    { loc: "773,2335,18", name: "34 St/ Herald Sq", imgName: ["/last_stop/Manhattan/34_street_herald_square_b_d_f_m_n_q_r.jpg" ]},
    { loc: "688,2330,18", name: "34 St/ Penn Station", imgName: ["/last_stop/Manhattan/34_street_penn_station_1_2_3-2.jpg" ]},
    { loc: "582,2330,18", name: "34 St/ Penn Station", imgName: ["/last_stop/Manhattan/34_street_penn_station_a_c_e.jpg" ]},
    { loc: "686,2366,18", name: "28 St", imgName: ["/last_stop/Manhattan/28_street_1.jpg" ]},
    { loc: "815,2375,18", name: "28 St", imgName: ["/last_stop/Manhattan/28_street_n_r-2.jpg", "/last_stop/Manhattan/28_street_n_r-3.jpg" ]},
    { loc: "879,2368,15", name: "28 St", imgName: ["/last_stop/Manhattan/28_street_6.jpg", "/last_stop/Manhattan/28_street_6-2.jpg" ]},
    { loc: "890,2399,18", name: "23 St", imgName: ["/last_stop/Manhattan/23_street_6.jpg" ]},
    { loc: "847,2404,18", name: "23 St", imgName: ["/last_stop/Manhattan/28_street_n_r.jpg" ]},
    { loc: "776,2402,18", name: "23 St", imgName: ["/last_stop/Manhattan/23_street_f_m.jpg", "/last_stop/Manhattan/23_street_f_m-2.jpg" ]},
    { loc: "683,2404,18", name: "23 St", imgName: ["/last_stop/Manhattan/23_street_1.jpg", "/last_stop/Manhattan/23_street_1-2.jpg" ]},
    { loc: "580,2397,18", name: "23 St", imgName: ["/last_stop/Manhattan/23_street_c_e.jpg" ]},
    { loc: "878,2456,18", name: "14 St/ Union Sq", imgName: ["/last_stop/Manhattan/14_street_union_square_l_n_q_r_4_5_6.jpg" ]},
    { loc: "774,2459,18", name: "6 Av/ 14 St", imgName: ["/last_stop/Manhattan/14_street_f_m_l.jpg" ]},
    { loc: "687,2464,14", name: "14 St", imgName: ["/last_stop/Manhattan/14_street_1_2_3.jpg" ]},
    { loc: "685,2436,14", name: "18 St", imgName: ["/last_stop/Manhattan/18_street_1.jpg", "/last_stop/Manhattan/18_street_1-2.jpg" ]},
    { loc: "591,2439,22", name: "8 Av/ 14 St", imgName: ["/last_stop/Manhattan/14_street_a_c_e_l.jpg", "/last_stop/Manhattan/14_street_a_c_e_l-3.jpg", "/last_stop/Manhattan/14_street_a_c_e_l-2.jpg" ]},
    { loc: "952,2455,18", name: "3 Av", imgName: ["/last_stop/Manhattan/3_avenue_l.jpg" ]},
    { loc: "1008,2455,18", name: "1 Av", line: ["L"], imgName: ["/last_stop/Manhattan/1_avenue_l.jpg" ]},
    { loc: "687,2535,18", name: "Christopher St/ Sheridan Sq", imgName: ["/last_stop/Manhattan/christopher_street_1.jpg" ]},
    { loc: "772,2543,18", name: "W 4 St/ Wash Sq", imgName: ["/last_stop/Manhattan/west_4_street_washington_square_a_c_e_b_d_f_m.jpg", "/last_stop/Manhattan/west_4_street_washington_square_a_c_e_b_d_f_m-3.jpg", "/last_stop/Manhattan/west_4_street_washington_square_a_c_e_b_d_f_m-2.jpg" ]},
    { loc: "870,2494,11", name: "8 St/ NYU", imgName: ["/last_stop/Manhattan/8_street_n_r.jpg" ]},
    { loc: "898,2485,11", name: "Astor Pl", imgName: ["/last_stop/Manhattan/astor_place_6-2.jpg", "/last_stop/Manhattan/astor_place_6.jpg" ]},
    { loc: "907,2551,11", name: "Bleecker St", imgName: ["/last_stop/Manhattan/bleecker_street_6_b_d_f_m-2.jpg" ]},
    { loc: "890,2571,11", name: "Bleecker St", imgName: ["/last_stop/Manhattan/bleecker_street_6_b_d_f_m.jpg" ]},
    { loc: "898,2595,11", name: "B&apos;way/ Lafayette St", imgName: ["/last_stop/Manhattan/broadway_lafayette_street_b_d_f_m_6.jpg" ]},
    { loc: "876,2608,11", name: "Prince St", imgName: ["/last_stop/Manhattan/prince_street_n_r-2.jpg", "/last_stop/Manhattan/prince_street_n_r.jpg" ]},
    { loc: "991,2600,18", name: "2 Av", line: ["F"], imgName: ["/last_stop/Manhattan/2_avenue_f.jpg" ]},
    { loc: "717,2606,18", name: "Houston St", imgName: ["/last_stop/Manhattan/houston_street_1.jpg" ]},
    { loc: "782,2627,18", name: "Spring St", imgName: ["/last_stop/Manhattan/spring_street_c_e.jpg" ]},
    { loc: "733,2658,18", name: "Canal St", imgName: ["/last_stop/Manhattan/canal_street_1.jpg" ]},
    { loc: "775,2664,18", name: "Canal St", imgName: ["/last_stop/Manhattan/canal_street_a_c_e.jpg" ]},
    { loc: "905,2638,18", name: "Spring St", imgName: ["/last_stop/Manhattan/spring_street_6.jpg", "/last_stop/Manhattan/spring_street_6-2.jpg" ]},
    { loc: "1033,2632,18", name: "Delancey St/ Essex St", imgName: ["/last_stop/Manhattan/delancy_street_f_m_j_z.jpg", "/last_stop/Manhattan/essex_street_f_m_j_z.jpg", "/last_stop/Manhattan/essex_street_f_m_j_z-2.jpg" ]},
    { loc: "866,2666,18", name: "Canal St", imgName: ["/last_stop/Manhattan/canal_street_n_q_r_6_j_z.jpg" ]},
    { loc: "913,2671,17", name: "Canal St", imgName: ["/last_stop/Manhattan/canal_street_n_q_r_6_j_z-2.jpg" ]},
    { loc: "961,2646,16", name: "Bowery St", imgName: ["/last_stop/Manhattan/bowery_street_j_z.jpg" ]},
    { loc: "987,2660,16", name: "Grand St", imgName: ["/last_stop/Manhattan/grand_street_b_d.jpg", "/last_stop/Manhattan/grand_street_b_d-2.jpg" ]},
    { loc: "1057,2675,18", name: "East Broadway", imgName: ["/last_stop/Manhattan/east_broadway_f.jpg", "/last_stop/Manhattan/east_broadway_f-3.jpg", "/last_stop/Manhattan/east_broadway_f-2.jpg" ]},
    { loc: "919,2737,18", name: "Chambers St", imgName: ["/last_stop/Manhattan/chambers_street_j_z_4_5_6.jpg" ]},
    { loc: "787,2732,14", name: "Chamber St", imgName: ["/last_stop/Manhattan/chambers_street_a_c_e_2_3-2.jpg", "chambers_street_a_c_e_2_3.jpg" ]},
    { loc: "754,2743,18", name: "Chamber St", imgName: ["/last_stop/Manhattan/chambers_street_1_2_3.jpg" ]},
    { loc: "890,2742,11", name: "Brooklyn Brigde/ City Hall", imgName: ["/last_stop/Manhattan/brooklyn_bridge_city_hall_4_5_6_j_z.jpg" ]},
    { loc: "847,2738,11", name: "City Hall", imgName: ["/last_stop/Manhattan/city_hall_r.jpg", "/last_stop/Manhattan/city_hall_r-2.jpg" ]},
    { loc: "752,2702,11", name: "Franklin St", imgName: ["/last_stop/Manhattan/franklin_street_1.jpg" ]},
    { loc: "806,2834,16", name: "Cortlandt St", imgName: ["/last_stop/Manhattan/courtland_street_r.jpg" ]},
    { loc: "891,2823,30", name: "Fulton St", imgName: ["/last_stop/Manhattan/fulton_street_a_c_j_z_2_3_4_5.jpg", "/last_stop/Manhattan/fulton_street_a_c_j_z_2_3_4_5-3.jpg", "/last_stop/Manhattan/fulton_street_a_c_j_z_2_3_4_5-2.jpg", "/last_stop/Manhattan/fulton_street_a_c_j_z_2_3_4_5-4.jpg" ]},
    { loc: "852,2872,16", name: "Wall St", imgName: ["/last_stop/Manhattan/wall_street_4_5.jpg", "/last_stop/Manhattan/wall_street_4_5-2.jpg" ]},
    { loc: "916,2864,16", name: "Wall St", imgName: ["/last_stop/Manhattan/wall_street_2_3.jpg" ]},
    { loc: "889,2899,16", name: "Broad St", imgName: ["/last_stop/Manhattan/broad_street_j_z.jpg" ]},
    { loc: "802,2884,16", name: "Rector St", imgName: ["/last_stop/Manhattan/rector_street_r.jpg" ]},
    { loc: "755,2884,16", name: "Rector St", imgName: ["/last_stop/Manhattan/rector_street_1.jpg" ]},
    { loc: "837,2926,16", name: "Bowling Green", imgName: ["/last_stop/Manhattan/bowling_green_4_5.jpg", "/last_stop/Manhattan/bowling_green_4_5-2.jpg" ]},
    { loc: "886,2959,13", name: "Whitehall St/ South Ferry", imgName: ["/last_stop/Manhattan/whitehall_street_south_ferry_r_1-4.jpg", "/last_stop/Manhattan/whitehall_street_south_ferry_r_1-2.jpg", "/last_stop/Manhattan/whitehall_street_south_ferry_r_1-1.jpg" ]},
    { loc: "862,2968,13", name: "South Ferry", imgName: ["/last_stop/Manhattan/south_ferry_1.jpg" ]},
    // Brooklyn
    { loc: "1919,3571,16", name: "Coney Island/ Stillwell Av", line: ["D", "F", "N", "Q"], imgName: ["/last_stop/Brooklyn/coney_island_stillwell_avenue_d_f_n_q.jpg"]},
    { loc: "1957,3551,16", name: "West 8 st/ NY Aquarium", line: ["F", "Q"], imgName: ["/last_stop/Brooklyn/west_8_street_new_york_aquarium_f_q.jpg", "/last_stop/Brooklyn/west_8_street_new_york_aquarium_f_q-2.jpg"]},
    { loc: "2020,3506,16", name: "Ocean Pkwy", line: ["Q"], imgName: ["/last_stop/Brooklyn/ocean_parkway_q.jpg", "/last_stop/Brooklyn/ocean_parkway_q-2.jpg", "/last_stop/Brooklyn/ocean_parkway_q-3.jpg"]},
    { loc: "2043,3470,16", name: "Brighton Beach", line: ["B", "Q"], imgName: ["/last_stop/Brooklyn/brighton_beach_b_q.jpg", "/last_stop/Brooklyn/brighton_beach_b_q-2.jpg", "/last_stop/Brooklyn/brighton_beach_b_q-3.jpg"]},
    { loc: "2032,3429,16", name: "Sheepshead Bay", line: ["B", "Q"], imgName: ["/last_stop/Brooklyn/sheepshead_bay_b_q.jpg", "/last_stop/Brooklyn/sheepshead_bay_b_q-2.jpg"]},
    { loc: "2006,3408,16", name: "Neck Rd", line: ["B, Q"], imgName: ["/last_stop/Brooklyn/neck_road_b_q.jpg", "/last_stop/Brooklyn/neck_road_b_q-2.jpg"]},
    { loc: "1982,3381,16", name: "Avenue U", line: ["B", "Q"], imgName: ["/last_stop/Brooklyn/avenue_u_b_q.jpg"]},
    { loc: "1938,3332,16", name: "Kings Hwy", line: ["B", "Q"], imgName: ["/last_stop/Brooklyn/kings_highway_b_q.jpg", "/last_stop/Brooklyn/kings_highway_b_q-2.jpg"]},
    { loc: "1886,3281,16", name: "Avenue M", line: ["B", "Q"], imgName: ["/last_stop/Brooklyn/avenue_m_b_q.jpg", "/last_stop/Brooklyn/avenue_m_b_q-2.jpg"]},
    { loc: "1847,3242,16", name: "Avenue J", line: ["B", "Q"], imgName: ["/last_stop/Brooklyn/avenue_j_b_q.jpg"]},
    { loc: "1808,3198,18", name: "Avenue H", line: ["B", "Q"], imgName: ["/last_stop/Brooklyn/avenue_h_b_q.jpg", "/last_stop/Brooklyn/avenue_h_b_q-2.jpg", "/last_stop/Brooklyn/avenue_h_b_q-3.jpg"]},
    { loc: "1779,3169,16", name: "Newkirk Plaza", line: ["B", "Q"], imgName: ["/last_stop/Brooklyn/newkirk_avenue_b_q.jpg", "/last_stop/Brooklyn/newkirk_avenue_b_q-2.jpg"]},
    { loc: "1750,3147,14", name: "Cortelyou Rd", line: ["B, Q"], imgName: ["/last_stop/Brooklyn/cortelyou_road_b_q.jpg", "/last_stop/Brooklyn/cortelyou_road_b_q-2.jpg"]},
    { loc: "1734,3123,14", name: "Beverley Rd", line: ["B", "Q"], imgName: ["/last_stop/Brooklyn/beverley_road_b_q.jpg"]},
    { loc: "1713,3104,14", name: "Church Av", line: ["B", "Q"], imgName: ["/last_stop/Brooklyn/church_avenue_b_q.jpg"]},
    { loc: "1703,3058,16", name: "Parkside Av", line: ["Q"], imgName: ["/last_stop/Brooklyn/parkside_avenue_q.jpg"]},
    { loc: "1966,3501,16", name: "Neptune Av", line: ["F"], imgName: ["/last_stop/Brooklyn/neptune_avenue_f.jpg"]},
    { loc: "1941,3479,16", name: "Avenue X", line: ["F"], imgName: ["/last_stop/Brooklyn/avenue_x_f.jpg"]},
    { loc: "1912,3444,16", name: "Avenue U", line: ["F"], imgName: ["/last_stop/Brooklyn/avenue_u_f.jpg", "/last_stop/Brooklyn/avenue_u_f-2.jpg"]},
    { loc: "1866,3396,16", name: "Kings Hwy", line: ["F"], imgName: ["/last_stop/Brooklyn/kings_highway_f.jpg", "/last_stop/Brooklyn/kings_highway_f-2.jpg"]},
    { loc: "1840,3378,16", name: "Avenue P", line: ["F"], imgName: ["/last_stop/Brooklyn/avenue_p_f.jpg", "/last_stop/Brooklyn/avenue_p_f-2.jpg"]},
    { loc: "1825,3349,16", name: "Avenue N", line: ["F"], imgName: ["/last_stop/Brooklyn/avenue_n_f.jpg", "/last_stop/Brooklyn/avenue_n_f-2.jpg", "/last_stop/Brooklyn/avenue_n_f-3.jpg"]},
    { loc: "1773,3302,16", name: "Bay Pkwy", line: ["F"], imgName: ["/last_stop/Brooklyn/bay_parkway_f.jpg", "/last_stop/Brooklyn/bay_parkway_f-2.jpg"]},
    { loc: "1747,3274,16", name: "Avenue I", line: ["F"], imgName: ["/last_stop/Brooklyn/avenue_i_f.jpg", "/last_stop/Brooklyn/avenue_i_f-2.jpg"]},
    { loc: "1723,3249,16", name: "18 Av", line: ["F"], imgName: ["/last_stop/Brooklyn/18_avenue_f-2.jpg", "/last_stop/Brooklyn/18_avenue_f-3.jpg", "/last_stop/Brooklyn/18_avenue_f-4.jpg", "/last_stop/Brooklyn/18_avenue_f.jpg"]},
    { loc: "1699,3227,16", name: "Ditmas Av", line: ["F"], imgName: ["/last_stop/Brooklyn/ditmas_avenue_f.jpg", "/last_stop/Brooklyn/ditmas_avenue_f-2.jpg", "/last_stop/Brooklyn/ditmas_avenue_f-3.jpg"]},
    { loc: "1656,3177,16", name: "Church Av", line: ["F", "G"], imgName: ["/last_stop/Brooklyn/church_avenue_f_g.jpg", "/last_stop/Brooklyn/church_avenue_f_g-2.jpg", "/last_stop/Brooklyn/church_avenue_f_g-3.jpg", "/last_stop/Brooklyn/church_avenue_f_g-4.jpg", "/last_stop/Brooklyn/church_avenue_f_g-5.jpg"]},
    { loc: "1641,3128,16", name: "Fort Hamilton Pkwy", line: ["F", "G"], imgName: ["/last_stop/Brooklyn/fort_hamilton_parkway_f_g.jpg", "/last_stop/Brooklyn/fort_hamilton_parkway_f_g-2.jpg", "/last_stop/Brooklyn/fort_hamilton_parkway_f_g-3.jpg", "/last_stop/Brooklyn/fort_hamilton_parkway_f_g-4.jpg"]},
    { loc: "1584,3038,16", name: "15 St/ Prospect Park", line: ["F", "G"], imgName: ["/last_stop/Brooklyn/15_street_prospect_park_f_g-2.jpg", "/last_stop/Brooklyn/15_street_prospect_park_f_g-3.jpg", "/last_stop/Brooklyn/15_street_prospect_park_f_g-4.jpg", "/last_stop/Brooklyn/15_street_prospect_park_f_g-5.jpg", "/last_stop/Brooklyn/15_street_prospect_park_f_g-6.jpg", "/last_stop/Brooklyn/15_street_prospect_park_f_g.jpg"]},
    { loc: "1873,3528,16", name: "Bay 50 St", line: ["D"], imgName: ["/last_stop/Brooklyn/bay_50_street_d.jpg", "/last_stop/Brooklyn/bay_50_street_d-2.jpg"]},
    { loc: "1836,3499,16", name: "25 Av", line: ["D"], imgName: ["/last_stop/Brooklyn/25_avenue_d.jpg", "/last_stop/Brooklyn/25_avenue_d-2.jpg"]},
    { loc: "1774,3494,16", name: "Bay Pkwy", line: ["D"], imgName: ["/last_stop/Brooklyn/bay_parkway_d.jpg"]},
    { loc: "1744,3490,14", name: "20 Av", line: ["D"], imgName: ["/last_stop/Brooklyn/20_avenue_d-2.jpg", "/last_stop/Brooklyn/20_avenue_d.jpg"]},
    { loc: "1714,3482,16", name: "18 Av", line: ["D"], imgName: ["/last_stop/Brooklyn/18_avenue_d-2.jpg", "/last_stop/Brooklyn/18_avenue_d-3.jpg", "/last_stop/Brooklyn/18_avenue_d.jpg"]},
    { loc: "1692,3455,16", name: "79 St", line: ["D"], imgName: ["/last_stop/Brooklyn/79_street_d.jpg", "/last_stop/Brooklyn/79_street_d-2.jpg"]},
    { loc: "1671,3418,16", name: "71 St", line: ["D"], imgName: ["/last_stop/Brooklyn/71_street_d.jpg", "/last_stop/Brooklyn/71_street_d-2.jpg"]},
    { loc: "1646,3371,16", name: "62 St", line: ["D"], imgName: ["/last_stop/Brooklyn/62_street_d.jpg", "/last_stop/Brooklyn/62_street_d-2.jpg"]},
    { loc: "1906,3493,16", name: "86 St", line: ["N"], imgName: ["/last_stop/Brooklyn/86_street_n.jpg"]},
    { loc: "1882,3472,16", name: "Avenue U", line: ["N"], imgName: ["/last_stop/Brooklyn/avenue_u_n.jpg"]},
    { loc: "1821,3413,16", name: "Kings Hwy", line: ["N"], imgName: ["/last_stop/Brooklyn/kings_highway_n.jpg"]},
    { loc: "1787,3381,16", name: "Bay Pkwy", line: ["N"], imgName: ["/last_stop/Brooklyn/bay_parkway_n.jpg"]},
    { loc: "1751,3368,16", name: "20 Av", line: ["N"], imgName: ["/last_stop/Brooklyn/20_avenue_n.jpg"]},
    { loc: "1717,3362,16", name: "18 Av", line: ["N"], imgName: ["/last_stop/Brooklyn/18_avenue_n.jpg"]},
    { loc: "1603,3365,16", name: "New Utrecht Av", line: ["N", "D"], imgName: ["/last_stop/Brooklyn/new_utrecht_avenue_n_d.jpg", "/last_stop/Brooklyn/new_utrecht_avenue_n_d-2.jpg"]},
    { loc: "1550,3362,16", name: "Fort Hamilton Pkwy", line: ["N"], imgName: ["/last_stop/Brooklyn/fort_hamilton_parkway_n.jpg"]},
    { loc: "1492,3363,16", name: "8 Av", line: ["N"], imgName: ["/last_stop/Brooklyn/8_avenue_n.jpg"]},
    { loc: "1612,3316,16", name: "55 St", line: ["D"], imgName: ["/last_stop/Brooklyn/55_street_d.jpg", "/last_stop/Brooklyn/55_street_d-2.jpg"]},
    { loc: "1591,3289,16", name: "50 St", line: ["D"], imgName: ["/last_stop/Brooklyn/50_street_d.jpg", "/last_stop/Brooklyn/50_street_d-2.jpg"]},
    { loc: "1566,3257,16", name: "Fort Hamilton Pkwy", line: ["D"], imgName: ["/last_stop/Brooklyn/fort_hamilton_parkway_d.jpg", "/last_stop/Brooklyn/fort_hamilton_parkway_d-2.jpg"]},
    { loc: "1535,3236,16", name: "9 Av", line: ["D"], imgName: ["/last_stop/Brooklyn/9_avenue_d.jpg", "/last_stop/Brooklyn/9_avenue_d-2.jpg"]},
    { loc: "1675,2982,16", name: "Prospect Park", line: ["B", "Q", "S"], imgName: ["/last_stop/Brooklyn/prospect_park_b_q_s.jpg", "/last_stop/Brooklyn/prospect_park_b_q_s-2.jpg"]},
    { loc: "1904,3104,16", name: "Flatbush Av/ Brooklyn College", line: ["2", "5"], imgName: ["/last_stop/Brooklyn/flatbush_avenue_2_5.jpg", "/last_stop/Brooklyn/flatbush_avenue_2_5-2.jpg", "/last_stop/Brooklyn/flatbush_avenue_2_5-3.jpg"]},
    { loc: "1860,3057,16", name: "Newkirk Av", line: ["2", "5"], imgName: ["/last_stop/Brooklyn/newkirk_avenue_2_5.jpg"]},
    { loc: "1837,3035,16", name: "Beverly Rd", line: ["2", "5"], imgName: ["/last_stop/Brooklyn/beverley_road_2_5.jpg"]},
    { loc: "1817,3008,16", name: "Church Av", line: ["2", "5"], imgName: ["/last_stop/Brooklyn/church_avenue_2_5.jpg", "/last_stop/Brooklyn/church_avenue_2_5-2.jpg", "/last_stop/Brooklyn/church_avenue_2_5-3.jpg"]},
    { loc: "1783,2979,16", name: "Winthrop St", line: ["2", "5"], imgName: ["/last_stop/Brooklyn/winthrop_street_2_5.jpg", "/last_stop/Brooklyn/winthrop_street_2_5-2.jpg"]},
    { loc: "1751,2940,16", name: "Sterling St", line: ["2", "5"], imgName: ["/last_stop/Brooklyn/sterling_street_2_5.jpg", "/last_stop/Brooklyn/sterling_street_2_5-2.jpg"]},
    { loc: "1724,2920,16", name: "President St", line: ["2", "5"], imgName: ["/last_stop/Brooklyn/president_street_2_5.jpg", "/last_stop/Brooklyn/president_street_2_5-2.jpg"]},
    { loc: "1744,2876,16", name: "Nostrand Av", line: ["3", "4"], imgName: ["/last_stop/Brooklyn/nostrand_avenue_3_4.jpg", "/last_stop/Brooklyn/nostrand_avenue_3_4-2.jpg"]},
    { loc: "1813,2838,16", name: "Kingston Av", line: ["3", "4"], imgName: ["/last_stop/Brooklyn/kingston_avenue_3_4.jpg"]},
    { loc: "1875,2793,16", name: "Crown Hts/ Utica Av", line: ["3", "4"], imgName: ["/last_stop/Brooklyn/utica_avenue_3_4.jpg", "/last_stop/Brooklyn/utica_avenue_3_4-2.jpg", "/last_stop/Brooklyn/utica_avenue_3_4-3.jpg"]},
    { loc: "1935,2771,16", name: "Sutter Av-Rutland Rd", line: ["3"], imgName: ["/last_stop/Brooklyn/sutter_avenue_rutland_road_3.jpg"]},
    { loc: "1994,2748,16", name: "Saratoga Av", line: ["3"], imgName: ["/last_stop/Brooklyn/saratoga_avenue_3.jpg", "/last_stop/Brooklyn/saratoga_avenue_3-2.jpg"]},
    { loc: "2036,2709,16", name: "Rockaway Av", line: ["3"], imgName: ["/last_stop/Brooklyn/rockaway_avenue_3.jpg"]},
    { loc: "2067,2681,16", name: "Junius St", line: ["3"], imgName: ["/last_stop/Brooklyn/junius_street_3.jpg"]},
    { loc: "2101,2676,16", name: "Livonia Av", line: ["L"], imgName: ["/last_stop/Brooklyn/livonia_avenue_l.jpg", "/last_stop/Brooklyn/livonia_avenue_l-2.jpg", "/last_stop/Brooklyn/livonia_avenue_l-3.jpg"]},
    { loc: "2126,2709,16", name: "New Lots Av", line: ["L"], imgName: ["/last_stop/Brooklyn/new_lots_avenue_l.jpg"]},
    { loc: "2151,2754,16", name: "East 105 St", line: ["L"], imgName: ["/last_stop/Brooklyn/east_105_street_l.jpg", "/last_stop/Brooklyn/east_105_street_l-2.jpg", "/last_stop/Brooklyn/east_105_street_l-3.jpg"]},
    { loc: "2164,2826,16", name: "Canarsie/ Rockaway Pkwy", line: ["L"], imgName: ["/last_stop/Brooklyn/rockaway_parkway_l.jpg", "/last_stop/Brooklyn/rockaway_parkway_l-2.jpg"]},
    { loc: "1473,3517,16", name: "Bay Ridge/ 95 St", line: ["R"], imgName: ["/last_stop/Brooklyn/95_street_r.jpg"]},
    { loc: "1464,3481,16", name: "86 St", line: ["R"], imgName: ["/last_stop/Brooklyn/86_street_r.jpg"]},
    { loc: "1437,3441,18", name: "77 St", line: ["R"], imgName: ["/last_stop/Brooklyn/77_street_r.jpg", "/last_stop/Brooklyn/77_street_r-2.jpg"]},
    { loc: "1430,3394,16", name: "Bay Ridge Av", line: ["R"], imgName: ["/last_stop/Brooklyn/bay_ridge_avenue_r.jpg", "/last_stop/Brooklyn/bay_ridge_avenue_r-2.jpg"]},
    { loc: "1436,3333,16", name: "59 St", line: ["N", "R"], imgName: ["/last_stop/Brooklyn/59_street_n_r.jpg", "/last_stop/Brooklyn/59_street_n_r-2.jpg"]},
    { loc: "1441,3292,16", name: "53 St", line: ["R"], imgName: ["/last_stop/Brooklyn/53_street_r.jpg", "/last_stop/Brooklyn/53_street_r-2.jpg"]},
    { loc: "1438,3247,16", name: "45 St", line: ["R"], imgName: ["/last_stop/Brooklyn/45_street_r.jpg", "/last_stop/Brooklyn/45_street_r-2.jpg"]},
    { loc: "1451,3204,16", name: "36 St", line: ["D", "N", "R"], imgName: ["/last_stop/Brooklyn/36_street_d_n_r.jpg"]},
    { loc: "1437,3126,16", name: "25 St", line: ["R"], imgName: ["/last_stop/Brooklyn/25_street_r.jpg"]},
    { loc: "1439,3072,16", name: "Prospect Av", line: ["R"], imgName: ["/last_stop/Brooklyn/prospect_avenue_r.jpg"]},
    { loc: "1534,3011,16", name: "7 Av", line: ["F", "G"], imgName: ["/last_stop/Brooklyn/7_avenue_f_g.jpg", "/last_stop/Brooklyn/7_avenue_f_g-2.jpg", "/last_stop/Brooklyn/7_avenue_f_g-3.jpg"]},
    { loc: "1443,2994,16", name: "4 Av-9 St", line: ["R"], imgName: ["/last_stop/Brooklyn/9_street_r.jpg"]},
    { loc: "1412,3003,16", name: "4 Av", line: ["F", "G", "R"], imgName: ["/last_stop/Brooklyn/4_avenue_9_street_f_g_r.jpg"]},
    { loc: "1377,3003,16", name: "Smith/ 9 Sts", line: ["F", "G"], imgName: ["/last_stop/Brooklyn/smith_9_streets_f_g.jpg"]},
    { loc: "1344,2970,17", name: "Carroll St", line: ["F", "G"], imgName: ["/last_stop/Brooklyn/carroll_street_f_g.jpg", "/last_stop/Brooklyn/carroll_street_f_g-2.jpg"]},
    { loc: "1340,2934,16", name: "Bergen St", line: ["F", "G"], imgName: ["/last_stop/Brooklyn/bergen_street_f_g.jpg", "/last_stop/Brooklyn/bergen_street_f_g-2.jpg", "/last_stop/Brooklyn/bergen_street_f_g-3.jpg", "/last_stop/Brooklyn/bergen_street_f_g-4.jpg"]},
    { loc: "1439,2952,16", name: "Union St", line: ["R"], imgName: ["/last_stop/Brooklyn/union_street_r.jpg", "/last_stop/Brooklyn/union_street_r-2.jpg"]},
    { loc: "1443,2899,16", name: "Atlantic Av-Pacific St", line: ["D", "N", "R"], imgName: ["/last_stop/Brooklyn/atlantic_avenue_pacific_street_d_n_r.jpg"]},
    { loc: "1483,2879,16", name: "Atlantic Av", line: ["2", "3", "4", "5", "B", "Q", "N", "R", "D"], imgName: ["/last_stop/Brooklyn/atlantic_avenue_barclays_center_2_3_4_5_b_q_n_r_d.jpg", "/last_stop/Brooklyn/atlantic_avenue_b_q_2_3_4_5-2.jpg", "/last_stop/Brooklyn/atlantic_avenue_b_q_2_3_4_5_n_r_d.jpg"]},
    { loc: "1527,2913,16", name: "Bergen St", line: ["2", "3"], imgName: ["/last_stop/Brooklyn/bergen_street_2_3.jpg", "/last_stop/Brooklyn/bergen_street_2_3-2.jpg", "/last_stop/Brooklyn/bergen_street_2_3-3.jpg"]},
    { loc: "1559,2898,16", name: "7 Av", line: ["B", "Q"], imgName: ["/last_stop/Brooklyn/7_avenue_b_q.jpg", "/last_stop/Brooklyn/7_avenue_b_q-2.jpg"]},
    { loc: "1569,2932,16", name: "Grand Army Plaza", line: ["2", "3"], imgName: ["/last_stop/Brooklyn/grand_army_plaza_2_3.jpg", "/last_stop/Brooklyn/grand_army_plaza_2_3-2.jpg"]},
    { loc: "1636,2928,16", name: "Eastern Pkwy/ Brooklyn Museum", line: ["2", "3"], imgName: ["/last_stop/Brooklyn/eastern_parkway_brooklyn_museum_2_3.jpg", "/last_stop/Brooklyn/eastern_parkway_brooklyn_museum_2_3-2.jpg", "/last_stop/Brooklyn/eastern_parkway_brooklyn_museum_2_3-3.jpg"]},
    { loc: "1671,2935,16", name: "Botanic Garden", line: ["S", "2", "3", "4", "5"], imgName: ["/last_stop/Brooklyn/botanic_garden_s_2_3_4_5.jpg"]},
    { loc: "1680,2902,16", name: "Franklin Av", line: ["S", "2", "3", "4", "5"], imgName: ["/last_stop/Brooklyn/franklin_avenue_2_3_4_5_s.jpg", "/last_stop/Brooklyn/franklin_avenue_2_3_4_5_s-2.jpg", "/last_stop/Brooklyn/franklin_avenue_2_3_4_5_s-3.jpg", "/last_stop/Brooklyn/franklin_avenue_2_3_4_5_s-4.jpg"]},
    { loc: "1651,2873,16", name: "Park Pl", line: ["S"], imgName: ["/last_stop/Brooklyn/park_place_s.jpg"]},
    { loc: "1387,2885,16", name: "Hoyt Schermerhorn", line: ["A", "C", "G"], imgName: ["/last_stop/Brooklyn/hoyt_schermerhorn_streets_a_c_g.jpg", "/last_stop/Brooklyn/hoyt_schermerhorn_streets_a_c_g-2.jpg"]},
    { loc: "1423,2852,16", name: "Nevins St", line: ["2", "3", "4", "5"], imgName: ["/last_stop/Brooklyn/nevins_street_2_3_4_5.jpg", "/last_stop/Brooklyn/nevins_street_2_3_4_5-2.jpg", "/last_stop/Brooklyn/nevins_street_2_3_4_5-3.jpg"]},
    { loc: "1371,2846,16", name: "Hoyt St", line: ["2", "3"], imgName: ["/last_stop/Brooklyn/hoyt_street_2_3.jpg", "/last_stop/Brooklyn/hoyt_street_2_3-2.jpg"]},
    { loc: "1489,2836,16", name: "Lafayette Av", line: ["A", "C"], imgName: ["/last_stop/Brooklyn/lafayette_avenue_a_c.jpg", "/last_stop/Brooklyn/lafayette_avenue_a_c-2.jpg", "/last_stop/Brooklyn/lafayette_avenue_a_c-3.jpg", "/last_stop/Brooklyn/lafayette_avenue_a_c-4.jpg"]},
    { loc: "1544,2812,16", name: "Clinton Washington Avs", line: ["A", "C"], imgName: ["/last_stop/Brooklyn/clinton_washington_avenues_a_c.jpg", "/last_stop/Brooklyn/clinton_washington_avenues_a_c-2.jpg"]},
    { loc: "1630,2777,16", name: "Franklin Av", line: ["A", "C", "S"], imgName: ["/last_stop/Brooklyn/franklin_avenue_a_c_s.jpg", "/last_stop/Brooklyn/franklin_avenue_a_c_s-2.jpg", "/last_stop/Brooklyn/franklin_avenue_a_c_s-3.jpg"]},
    { loc: "1679,2754,16", name: "Nostrand Av", line: ["A", "C"], imgName: ["/last_stop/Brooklyn/nostrand_avenue_a_c.jpg", "/last_stop/Brooklyn/nostrand_avenue_a_c-2.jpg"]},
    { loc: "1713,2718,16", name: "Kingston/ Throop Avs", line: ["A", "C"], imgName: ["/last_stop/Brooklyn/kingston_throop_avenues_a_c.jpg", "/last_stop/Brooklyn/kingston_throop_avenues_a_c-2.jpg"]},
    { loc: "1322,2850,16", name: "Borough Hall", line: ["2", "3", "4", "5"], imgName: ["/last_stop/Brooklyn/bourough_hall_2_3_4_5.jpg", "/last_stop/Brooklyn/bourough_hall_2_3_4_5-2.jpg"]},
    { loc: "1290,2848,16", name: "Court St", line: ["R"], imgName: ["/last_stop/Brooklyn/court_street_r.jpg"]},
    { loc: "1318,2817,16", name: "Jay St/ MetroTech", line: ["A", "C", "F", "R"], imgName: ["/last_stop/Brooklyn/jay_street_metro_tech_a_c_f_r.jpg", "/last_stop/Brooklyn/jay_street_metro_tech_a_c_f_r-2.jpg", "/last_stop/Brooklyn/jay_street_metro_tech_a_c_f_r-3.jpg", "/last_stop/Brooklyn/jay_street_metro_tech_a_c_f_r-4.jpg"]},
    { loc: "1220,2834,16", name: "Clark St", line: ["2", "3"], imgName: ["/last_stop/Brooklyn/clark_street_2_3.jpg"]},
    { loc: "1234,2767,16", name: "High St", line: ["A", "C"], imgName: ["/last_stop/Brooklyn/high_street_brooklyn_bridge_a_c.jpg", "/last_stop/Brooklyn/high_street_brooklyn_bridge_a_c-2.jpg"]},
    { loc: "1418,2813,16", name: "Dekalb Av", line: ["B", "Q", "R"], imgName: ["/last_stop/Brooklyn/dekalb_avenue_b_q_r.jpg", "/last_stop/Brooklyn/dekalb_avenue_b_q_r-2.jpg", "/last_stop/Brooklyn/dekalb_avenue_b_q_r-3.jpg"]},
    { loc: "1467,2812,16", name: "Fulton St", line: ["G"], imgName: ["/last_stop/Brooklyn/fulton_street_g.jpg", "/last_stop/Brooklyn/fulton_street_g-2.jpg", "/last_stop/Brooklyn/fulton_street_g-3.jpg"]},
    { loc: "1282,2711,16", name: "York St", line: ["F"], imgName: ["/last_stop/Brooklyn/york_street_f.jpg"]},
    { loc: "1514,2788,16", name: "Clinton Washington Avs", line: ["G"], imgName: ["/last_stop/Brooklyn/clinton_washington_avenues_g.jpg", "/last_stop/Brooklyn/clinton_washington_avenues_g-2.jpg", "/last_stop/Brooklyn/clinton_washington_avenues_g-3.jpg", "/last_stop/Brooklyn/clinton_washington_avenues_g-4.jpg"]},
    { loc: "1546,2749,16", name: "Classon Av", line: ["G"], imgName: ["/last_stop/Brooklyn/classon_avenue_g.jpg", "/last_stop/Brooklyn/classon_avenue_g-2.jpg"]},
    { loc: "1587,2712,16", name: "Bedford Nostrand Avs", line: ["G"], imgName: ["/last_stop/Brooklyn/bedford_nostrand_avenues_g.jpg", "/last_stop/Brooklyn/bedford_nostrand_avenues_g-2.jpg", "/last_stop/Brooklyn/bedford_nostrand_avenues_g-3.jpg"]},
    { loc: "1549,2643,16", name: "Myrtle Willoughby Avs", line: ["G"], imgName: ["/last_stop/Brooklyn/myrtle_willoughby_avenues_g.jpg", "/last_stop/Brooklyn/myrtle_willoughby_avenues_g-2.jpg"]},
    { loc: "1496,2595,16", name: "Flushing Av", line: ["G"], imgName: ["/last_stop/Brooklyn/flushing_avenue_g.jpg", "/last_stop/Brooklyn/flushing_avenue_g-2.jpg"]},
    { loc: "1353,2575,16", name: "Marcy Av", line: ["J", "M", "Z"], imgName: ["/last_stop/Brooklyn/marcy_avenue_j_m_z.jpg", "/last_stop/Brooklyn/marcy_avenue_j_m_z-2.jpg"]},
    { loc: "1420,2568,16", name: "Hewes St", line: ["J", "M"], imgName: ["/last_stop/Brooklyn/hewes_street_j_m.jpg"]},
    { loc: "1449,2553,16", name: "Broadway", line: ["G"], imgName: ["/last_stop/Brooklyn/broadway_g.jpg", "/last_stop/Brooklyn/broadway_g-2.jpg"]},
    { loc: "1481,2558,16", name: "Lorimer St", line: ["J", "M"], imgName: ["/last_stop/Brooklyn/lorimer_street_j_m.jpg", "/last_stop/Brooklyn/lorimer_street_j_m-2.jpg", "/last_stop/Brooklyn/lorimer_street_j_m-3.jpg"]},
    { loc: "1519,2558,16", name: "Flushing Av", line: ["J", "M"], imgName: ["/last_stop/Brooklyn/flushing_avenue_j_m.jpg", "/last_stop/Brooklyn/flushing_avenue_j_m-2.jpg"]},
    { loc: "1627,2556,16", name: "Myrtle Av", line: ["J", "M", "Z"], imgName: ["/last_stop/Brooklyn/myrtle_avenue_j_m_z.jpg", "/last_stop/Brooklyn/myrtle_avenue_j_m_z-2.jpg"]},
    { loc: "1708,2556,16", name: "Kosciuszko St", line: ["J"], imgName: ["/last_stop/Brooklyn/kosciuszko_street_j.jpg", "/last_stop/Brooklyn/kosciuszko_street_j-2.jpg"]},
    { loc: "1778,2550,16", name: "Gates Av", line: ["J", "Z"], imgName: ["/last_stop/Brooklyn/gates_avenue_j_z.jpg", "/last_stop/Brooklyn/gates_avenue_j_z-2.jpg"]},
    { loc: "1824,2546,16", name: "Halsey St", line: ["J"], imgName: ["/last_stop/Brooklyn/halsey_street_j.jpg"]},
    { loc: "1868,2545,16", name: "Chauncey St", line: ["J", "Z"], imgName: ["/last_stop/Brooklyn/chauncey_street_j_z.jpg", "/last_stop/Brooklyn/chauncey_street_j_z-2.jpg"]},
    { loc: "1951,2542,16", name: "Broadway Junction", line: ["L", "C", "A", "J", "M"], imgName: ["/last_stop/Brooklyn/broadway_junction_a_c_l_j_m.jpg", "/last_stop/Brooklyn/broadway_junction_a_c_l_j_m-2.jpg"]},
    { loc: "1991,2523,16", name: "Alabama Av", line: ["J"], imgName: ["/last_stop/Brooklyn/alabama_avenue_j.jpg", "/last_stop/Brooklyn/alabama_avenue_j-2.jpg"]},
    { loc: "2032,2494,16", name: "Van Siclen Av", line: ["J", "Z"], imgName: ["/last_stop/Brooklyn/van_siclen_avenue_j_z.jpg", "/last_stop/Brooklyn/van_siclen_avenue_j_z-2.jpg", "/last_stop/Brooklyn/van_siclen_avenue_j_z-3.jpg"]},
    { loc: "2062,2472,16", name: "Cleveland St", line: ["J"], imgName: ["/last_stop/Brooklyn/cleveland_street_j.jpg", "/last_stop/Brooklyn/cleveland_street_j-2.jpg"]},
    { loc: "2083,2442,16", name: "Norwood Av", line: ["J", "Z"], imgName: ["/last_stop/Brooklyn/norwood_avenue_j_z.jpg", "/last_stop/Brooklyn/norwood_avenue_j_z-2.jpg"]},
    { loc: "2088,2408,16", name: "Crescent St", line: ["J", "Z"], imgName: ["/last_stop/Brooklyn/crescent_street_j_z.jpg"]},
    { loc: "2074,2372,16", name: "Cypress Hills", line: ["J", "Z"], imgName: ["/last_stop/Brooklyn/cypress_hills_j.jpg", "/last_stop/Brooklyn/cypress_hills_j_z-2.jpg"]},
    { loc: "2205,2448,16", name: "Grant Av", line: ["A", "C"], imgName: ["/last_stop/Brooklyn/grant_avenue_a_c.jpg"]},
    { loc: "2174,2484,16", name: "Euclid Av", line: ["A", "C"], imgName: ["/last_stop/Brooklyn/euclid_avenue_a_c.jpg", "/last_stop/Brooklyn/euclid_avenue_a_c-2.jpg", "/last_stop/Brooklyn/euclid_avenue_a_c-3.jpg"]},
    { loc: "2140,2524,16", name: "Shepherd Av", line: ["A", "C"], imgName: ["/last_stop/Brooklyn/shepherd_avenue_a_c.jpg", "/last_stop/Brooklyn/shepherd_avenue_a_c-2.jpg"]},
    { loc: "2089,2549,16", name: "Van Siclen Av", line: ["A", "C"], imgName: ["/last_stop/Brooklyn/van_siclen_avenue_a_c.jpg", "/last_stop/Brooklyn/van_siclen_avenue_a_c-2.jpg"]},
    { loc: "2050,2548,16", name: "Liberty Av", line: ["A", "C"], imgName: ["/last_stop/Brooklyn/liberty_avenue_a_c.jpg", "/last_stop/Brooklyn/liberty_avenue_a_c-2.jpg", "/last_stop/Brooklyn/liberty_avenue_a_c-3.jpg"]},
    { loc: "2052,2635,16", name: "Sutter Av", line: ["L"], imgName: ["/last_stop/Brooklyn/sutter_avenue_l.jpg"]},
    { loc: "1984,2579,16", name: "Atlantic Av", line: ["L"], imgName: ["/last_stop/Brooklyn/atlantic_avenue_l.jpg", "/last_stop/Brooklyn/atlantic_avenue_l-2.jpg", "/last_stop/Brooklyn/atlantic_avenue_l-3.jpg"]},
    { loc: "2116,2646,16", name: "Pennsylvania Av", line: ["3"], imgName: ["/last_stop/Brooklyn/pennsylvania_avenue_3.jpg", "/last_stop/Brooklyn/pennsylvania_avenue_3-2.jpg"]},
    { loc: "2137,2622,16", name: "Van Siclen Av", line: ["3"], imgName: ["/last_stop/Brooklyn/van_siclen_3.jpg"]},
    { loc: "2162,2597,16", name: "New Lots Av", line: ["3"], imgName: ["/last_stop/Brooklyn/new_lots_avenue_3.jpg"]},
    { loc: "1891,2589,16", name: "Rockaway Av", line: ["A", "C"], imgName: ["/last_stop/Brooklyn/rockaway_avenue_a_c.jpg", "/last_stop/Brooklyn/rockaway_avenue_a_c-2.jpg", "/last_stop/Brooklyn/rockaway_avenue_a_c-3.jpg"]},
    { loc: "1846,2626,16", name: "Ralph Av", line: ["A", "C"], imgName: ["/last_stop/Brooklyn/ralph_avenue_a_c.jpg", "/last_stop/Brooklyn/ralph_avenue_a_c-2.jpg"]},
    { loc: "1788,2662,16", name: "Utica Av", line: ["A", "C"], imgName: ["/last_stop/Brooklyn/utica_avenue_a_c.jpg", "/last_stop/Brooklyn/utica_avenue_a_c-2.jpg"]},
    { loc: "1909,2519,16", name: "Bushwick Av/ Aberdeen St", line: ["L"], imgName: ["/last_stop/Brooklyn/bushwick_avenue_aberdeen_street_l.jpg", "/last_stop/Brooklyn/bushwick_avenue_aberdeen_street_l-2.jpg"]},
    { loc: "1865,2479,16", name: "Wilson Av", line: ["L"], imgName: ["/last_stop/Brooklyn/wilson_avenue_l.jpg", "/last_stop/Brooklyn/wilson_avenue_l-2.jpg"]},
    { loc: "1824,2448,16", name: "Halsey St", line: ["L"], imgName: ["/last_stop/Brooklyn/halsey_street_l.jpg", "/last_stop/Brooklyn/halsey_street_l-2.jpg", "/last_stop/Brooklyn/halsey_street_l-3.jpg"]},
    { loc: "1752,2436,16", name: "Myrtle Wyckoff Avs", line: ["L", "M"], imgName: ["/last_stop/Brooklyn/myrtle_wyckoff_avenue_l_m.jpg", "/last_stop/Brooklyn/myrtle_wyckoff_avenue_l_m-2.jpg", "/last_stop/Brooklyn/myrtle_wyckoff_avenue_l_m-3.jpg"]},
    { loc: "1727,2475,16", name: "Knickerbocker Av", line: ["M"], imgName: ["/last_stop/Brooklyn/knickerbocker_avenue_m.jpg"]},
    { loc: "1692,2502,16", name: "Central Av", line: ["M"], imgName: ["/last_stop/Brooklyn/central_avenue_m.jpg", "/last_stop/Brooklyn/central_avenue_m-2.jpg"]},
    { loc: "1686,2434,16", name: "DeKalb Av", line: ["L"], imgName: ["/last_stop/Brooklyn/dekalb_avenue_l.jpg", "/last_stop/Brooklyn/dekalb_avenue_l-2.jpg"]},
    { loc: "1633,2434,16", name: "Jefferson St", line: ["L"], imgName: ["/last_stop/Brooklyn/jefferson_street_l.jpg", "/last_stop/Brooklyn/jefferson_street_l-2.jpg", "/last_stop/Brooklyn/jefferson_street_l-3.jpg"]},
    { loc: "1553,2476,16", name: "Morgan Av", line: ["L"], imgName: ["/last_stop/Brooklyn/morgan_avenue_l.jpg", "/last_stop/Brooklyn/morgan_avenue_l-2.jpg", "/last_stop/Brooklyn/morgan_avenue_l-3.jpg"]},
    { loc: "1515,2473,16", name: "Montrose Av", line: ["L"], imgName: ["/last_stop/Brooklyn/montrose_avenue_l.jpg"]},
    { loc: "1469,2455,16", name: "Grand St", line: ["L"], imgName: ["/last_stop/Brooklyn/grand_street_l.jpg", "/last_stop/Brooklyn/grand_street_l-2.jpg"]},
    { loc: "1424,2443,16", name: "Graham Av", line: ["L"], imgName: ["/last_stop/Brooklyn/graham_avenue_l.jpg"]},
    { loc: "1363,2490,16", name: "Metropolitan Av", line: ["G", "L"], imgName: ["/last_stop/Brooklyn/metropolitan_avenue_g_l.jpg"]},
    { loc: "1355,2458,16", name: "Lorimer St", line: ["L", "G"], imgName: ["/last_stop/Brooklyn/lorimer_street_l_g.jpg"]},
    { loc: "1248,2457,16", name: "Bedford Av", line: ["L"], imgName: ["/last_stop/Brooklyn/bedford_avenue_l.jpg", "/last_stop/Brooklyn/bedford_avenue_l-2.jpg"]},
    { loc: "1295,2432,16", name: "Nassau Av", line: ["G"], imgName: ["/last_stop/Brooklyn/nassau_avenue_g.jpg", "/last_stop/Brooklyn/nassau_avenue_g-2.jpg", "/last_stop/Brooklyn/nassau_avenue_g-3.jpg", "/last_stop/Brooklyn/nassau_avenue_g-4.jpg"]},
    { loc: "1248,2397,16", name: "Greenpoint Av", line: ["G"], imgName: ["/last_stop/Brooklyn/greenpoint_avenue_g.jpg", "/last_stop/Brooklyn/greenpoint_avenue_g-2.jpg", "/last_stop/Brooklyn/greenpoint_avenue_g-3.jpg", "/last_stop/Brooklyn/greenpoint_avenue_g-4.jpg", "/last_stop/Brooklyn/greenpoint_avenue_g-5.jpg"]},
		// Queens
    { loc: "1246,1830,24", name: "Astoria Ditmars Blvd", imgName: ["/last_stop/Queens/ditmars_boulevard_n_q.jpg", "/last_stop/Queens/ditmars_boulevard_n_q-2.jpg", "/last_stop/Queens/ditmars_boulevard_n_q-3.jpg"]},
    { loc: "1242,1910,16", name: "Astoria Blvd", imgName: ["/last_stop/Queens/astoria_boulevard_n_q.jpg"]},
    { loc: "1238,1950,16", name: "30 Av", imgName: ["/last_stop/Queens/30_avenue_n_q-2.jpg", "/last_stop/Queens/30_avenue_n_q.jpg"]},
    { loc: "1240,2005,16", name: "Broadway", imgName: ["/last_stop/Queens/broadway_n_q-2.jpg", "/last_stop/Queens/broadway_n_q.jpg"]},
    { loc: "1224,2058,16", name: "36 Av", imgName: ["/last_stop/Queens/36_avenue_n_q.jpg"]},
    { loc: "1220,2098,16", name: "39 Av", imgName: ["/last_stop/Queens/39_avenue_n_q.jpg", "/last_stop/Queens/39_avenue_n_q-2.jpg"]},
    { loc: "1166,2113,16", name: "21 St/ Queens bridge", imgName: ["/last_stop/Queens/21_street_queensbridge_f.jpg", "/last_stop/Queens/21_street_queensbridge_f-2.jpg", "/last_stop/Queens/21_street_queensbridge_f-3.jpg"]},
    { loc: "1193,2140,16", name: "Queensboro Plaza", imgName: ["/last_stop/Queens/queensboro_plaza_n_q_7-2.jpg", "/last_stop/Queens/queensboro_plaza_n_q_7.jpg"]},
    { loc: "1784,1742,16", name: "Flushing Main St", imgName: ["/last_stop/Queens/main_street_7-2.jpg", "/last_stop/Queens/main_street_7.jpg"]},
    { loc: "1742,1810,18", name: "Mets/ Willets Point", imgName: ["/last_stop/Queens/willets_point_mets_7.jpg", "/last_stop/Queens/willets_point_mets_7-2.jpg"]},
    { loc: "1717,1851,16", name: "111 St", imgName: ["/last_stop/Queens/111_street_7.jpg", "/last_stop/Queens/111_street_7-2.jpg"]},
    { loc: "1678,1901,16", name: "103 St/ Corona Plaza", imgName: ["/last_stop/Queens/103_street_corona_plaza_7.jpg", "/last_stop/Queens/103_street_corona_plaza_7-2.jpg"]},
    { loc: "1642,1937,17", name: "Junction Blvd", imgName: ["/last_stop/Queens/junction_boulevard_7-2.jpg", "/last_stop/Queens/junction_boulevard_7.jpg"]},
    { loc: "1625,1963,16", name: "90 St/ Elmhurst Av", imgName: ["/last_stop/Queens/90_street_elmhurst_avenue_7-3.jpg", "/last_stop/Queens/90_street_elmhurst_avenue_7.jpg", "/last_stop/Queens/90_street_elmhurst_avenue_7-2.jpg"]},
    { loc: "1577,2002,16", name: "82 St/  Jackson Hts", imgName: ["/last_stop/Queens/82_street_7-2.jpg", "/last_stop/Queens/82_street_7.jpg"]},
    { loc: "1534,2015,16", name: "74 St/ Broadway", imgName: ["/last_stop/Queens/74_street_broadway_7_e_f_m_r.jpg"]},
    { loc: "1481,2017,16", name: "65 St", imgName: ["/last_stop/Queens/65_street_m_r.jpg", "/last_stop/Queens/65_street_m_r-2.jpg"]},
    { loc: "1417,2014,16", name: "Northen Blvd", imgName: ["/last_stop/Queens/northern_boulevard_m_r.jpg", "/last_stop/Queens/northern_boulevard_m_r-2.jpg"]},
    { loc: "1361,2009,16", name: "46 St", imgName: ["/last_stop/Queens/46_street_m_r.jpg", "/last_stop/Queens/46_street_m_r-2.jpg"]},
    { loc: "1312,2023,16", name: "Steinway St", imgName: ["/last_stop/Queens/steinway_street_m_r.jpg", "/last_stop/Queens/steinway_street_m_r-2.jpg"]},
    { loc: "1587,2052,16", name: "Elmhurst Av", imgName: ["/last_stop/Queens/elmhurst_avenue_m_r-3.jpg", "/last_stop/Queens/elmhurst_avenue_m_r-4.jpg", "/last_stop/Queens/elmhurst_avenue_m_r-2.jpg"]},
    { loc: "1539,2049,16", name: "Jackson Hts/ Roosevelt  Av", imgName: ["/last_stop/Queens/roosevelt_avenue_jackson_heights_e_f_m_r_7-2-3.jpg", "/last_stop/Queens/roosevelt_avenue_jackson_heights_e_f_m_r_7-2-2.jpg", "/last_stop/Queens/roosevelt_avenue_jackson_heights_e_f_m_r_7-2.jpg"]},
    { loc: "1659,2067,16", name: "Grand Av/ Newton", imgName: ["/last_stop/Queens/grand_avenue_newton_m_r.jpg", "/last_stop/Queens/grand_avenue_newton_m_r-5.jpg", "/last_stop/Queens/grand_avenue_newton_m_r-4.jpg", "/last_stop/Queens/grand_avenue_newton_m_r-3.jpg", "/last_stop/Queens/grand_avenue_newton_m_r-2.jpg"]},
    { loc: "1729,2060,16", name: "Woodhaven Blvd", imgName: ["/last_stop/Queens/woodhaven_boulevard_m_r.jpg", "/last_stop/Queens/woodhaven_boulevard_m_r-2.jpg"]},
    { loc: "1809,2055,16", name: "63 Dr/ Rego Park", imgName: ["/last_stop/Queens/63_drive_rego_park_m_r.jpg", "/last_stop/Queens/63_drive_rego_park_m_r-3.jpg", "/last_stop/Queens/63_drive_rego_park_m_r-2.jpg"]},
    { loc: "1889,2055,16", name: "67 Av", imgName: ["/last_stop/Queens/67_avenue_m_r-2.jpg", "/last_stop/Queens/67_avenue_m_r.jpg"]},
    { loc: "1958,2038,16", name: "Forest Hills/ 71 Av", imgName: ["/last_stop/Queens/71_continental_avenues_e_f_m_r.jpg"]},
    { loc: "2094,2051,16", name: "75 Av", imgName: ["/last_stop/Queens/75_avenue_e_f-2.jpg", "/last_stop/Queens/75_avenue_e_f.jpg"]},
    { loc: "2184,2044,16", name: "Kew Gardens/ Union Tpke", imgName: ["/last_stop/Queens/union_turnpike_kew_gardens_e_f-2.jpg", "/last_stop/Queens/union_turnpike_kew_gardens_e_f.jpg", "/last_stop/Queens/union_turnpike_kew_gardens_e_f-3.jpg", "/last_stop/Queens/union_turnpike_kew_gardens_e_f-2.jpg"]},
    { loc: "2274,2034,16", name: "Brairwood/ Van Wyck Blvd", imgName: ["/last_stop/Queens/briarwood_van_wyck_e_f.jpg", "/last_stop/Queens/briarwood_van_wyck_e_f-2.jpg"]},
    { loc: "2347,1987,16", name: "Sutphin Blvd", imgName: ["/last_stop/Queens/sutphin_boulevard_f-4.jpg", "/last_stop/Queens/sutphin_boulevard_f.jpg", "/last_stop/Queens/sutphin_boulevard_f-3.jpg", "/last_stop/Queens/sutphin_boulevard_f-2.jpg"]},
    { loc: "2376,1957,16", name: "Parson Blvd", imgName: ["/last_stop/Queens/parsons_boulevard_f-2.jpg", "/last_stop/Queens/parsons_boulevard_f.jpg", "/last_stop/Queens/parsons_boulevard_f-3.jpg", "/last_stop/Queens/parsons_boulevard_f-4.jpg"]},
    { loc: "2411,1927,16", name: "169 St", imgName: ["/last_stop/Queens/169_street_f.jpg", "/last_stop/Queens/169_street_f-2.jpg", "/last_stop/Queens/169_street_f-3.jpg", "/last_stop/Queens/169_street_f-4.jpg"]},
    { loc: "2440,1887,16", name: "Jamaica/ 179 St", imgName: ["/last_stop/Queens/179_street_jamaica_f-5.jpg", "/last_stop/Queens/179_street_jamaica_f.jpg", "/last_stop/Queens/179_street_jamaica_f-4.jpg", "/last_stop/Queens/179_street_jamaica_f-3.jpg", "/last_stop/Queens/179_street_jamaica_f-2.jpg"]},
    { loc: "2307,2070,16", name: "Jamaica/ Van Wyck Blvd", imgName: ["/last_stop/Queens/jamaica_van_wyck_e.jpg", "/last_stop/Queens/jamaica_van_wyck_e-3.jpg", "/last_stop/Queens/jamaica_van_wyck_e-2.jpg"]},
    { loc: "1488,2059,16", name: "69 St", imgName: ["/last_stop/Queens/69_street_fisk_avenue_7.jpg", "/last_stop/Queens/69_street_fisk_avenue_7-2.jpg"]},
    { loc: "1465,2092,16", name: "Woodside/ 61 St", imgName: ["/last_stop/Queens/61_street_woodside_7-2.jpg", "/last_stop/Queens/61_street_woodside_7-3.jpg", "/last_stop/Queens/61_street_woodside_7.jpg"]},
    { loc: "1430,2112,16", name: "52 St", imgName: ["/last_stop/Queens/52_street_lincoln_avenue_7.jpg"]},
    { loc: "1404,2131,16", name: "46 St Bliss St", imgName: ["/last_stop/Queens/46_street_bliss_street_7-3.jpg", "/last_stop/Queens/46_street_bliss_street_7-2.jpg"]},
    { loc: "1357,2149,16", name: "40 St/ Lowery St", imgName: ["/last_stop/Queens/40_street_lowery_street_7.jpg", "/last_stop/Queens/40_street_lowery_street_7-2.jpg"]},
    { loc: "1164,2109,16", name: "21 St Queens-Bridge", imgName: ["/last_stop/Queens/21_street_queensbridge_f.jpg", "/last_stop/Queens/21_street_queensbridge_f-2.jpg", "/last_stop/Queens/21_street_queensbridge_f-3.jpg"]},
    { loc: "1193,2143,16", name: "Queensboro Plaza", imgName: ["/last_stop/Queens/queensboro_plaza_n_q_7-2.jpg", "/last_stop/Queens/queensboro_plaza_n_q_7.jpg"]},
    { loc: "1223,2162,16", name: "Queens Plaza", imgName: ["/last_stop/Queens/queens_plaza_e_m_r.jpg", "/last_stop/Queens/queens_plaza_e_m_r-2.jpg", "/last_stop/Queens/queens_plaza_e_m_r-3.jpg"]},
    { loc: "1283,2152,16", name: "33 St/ Rawson St", imgName: ["/last_stop/Queens/33_street_rawson_street_7.jpg", "/last_stop/Queens/33_street_rawson_street_7-2.jpg"]},
    { loc: "1155,2204,16", name: "Court St/ 23 St", imgName: ["/last_stop/Queens/court_square_23_street_e_m_g-3.jpg", "/last_stop/Queens/court_square_23_street_e_m_g-2.jpg", "/last_stop/Queens/court_square_23_street_e_m_g.jpg"]},
    { loc: "1188,2222,16", name: "Court Sq", imgName: ["/last_stop/Queens/court_square_g_e_7_m-2.jpg", "/last_stop/Queens/court_square_g_e_7_m.jpg", "/last_stop/Queens/court_square_g_e_m.jpg", "/last_stop/Queens/court_square_7.jpg"]},
    { loc: "1170,2261,16", name: "21 St", imgName: ["/last_stop/Queens/21_street_van_alst_g.jpg", "/last_stop/Queens/21_street_van_alst_g-2.jpg"]},
    { loc: "1193,2279,16", name: "Hunters Point Av", imgName: ["/last_stop/Queens/hunters_point_7.jpg"]},
    { loc: "1130,2280,16", name: "Vernon Blvd/ Jackson Av", imgName: ["/last_stop/Queens/vernon_boulevard_jackson_avenue_7-2.jpg", "/last_stop/Queens/vernon_boulevard_jackson_avenue_7.jpg"]},
    { loc: "2085,2329,16", name: "75 St-Elderts Ln", imgName: ["/last_stop/Queens/75_street_elderts_lane_j_z.jpg"]},
    { loc: "2115,2308,16", name: "85 St-Forest Pkwy", imgName: ["/last_stop/Queens/85_street_forest_parkway_j.jpg", "/last_stop/Queens/85_street_forest_parkway_j-2.jpg"]},
    { loc: "2146,2278,16", name: "Woodhaven Blvd", imgName: ["/last_stop/Queens/woodhaven_boulevard_j_z.jpg", "/last_stop/Queens/woodhaven_boulevard_j_z-2.jpg"]},
    { loc: "2192,2240,16", name: "104 St", imgName: ["/last_stop/Queens/104_street_j_z.jpg", "/last_stop/Queens/104_street_j_z-2.jpg"]},
    { loc: "2230,2201,16", name: "111 St", imgName: ["/last_stop/Queens/111_street_j-2.jpg", "/last_stop/Queens/111_street_j.jpg"]},
    { loc: "2264,2171,16", name: "121 St", imgName: ["/last_stop/Queens/121_street_j_z.jpg", "/last_stop/Queens/121_street_j_z-2.jpg"]},
    { loc: "2406,2084,16", name: "Sutphin Blvd/ Archer Av/ JFK Airport", imgName: ["/last_stop/Queens/sutphin_boulevard_archer_avenue_jfk_airport_e_j_z-2.jpg", "/last_stop/Queens/sutphin_boulevard_archer_avenue_jfk_airport_e_j_z.jpg"]},
    { loc: "2451,2049,16", name: "Jamaica Center/ Parsons/Archer", imgName: ["/last_stop/Queens/jamaica_center_parsons_archer_avenues_e_j_z-4.jpg", "/last_stop/Queens/jamaica_center_parsons_archer_avenues_e_j_z.jpg", "/last_stop/Queens/jamaica_center_parsons_archer_avenues_e_j_z-6.jpg", "/last_stop/Queens/jamaica_center_parsons_archer_avenues_e_j_z-3.jpg"]},
    { loc: "2412,2230,16", name: "Ozone Park/ Lefferts Blvd", imgName: ["/last_stop/Queens/lefferts_boulevard_a-2.jpg", "/last_stop/Queens/lefferts_boulevard_a.jpg"]},
    { loc: "2372,2262,16", name: "111 St", imgName: ["/last_stop/Queens/111_street_greenwood_avenue_a.jpg", "/last_stop/Queens/111_street_greenwood_avenue_a-2.jpg"]},
    { loc: "2334,2295,16", name: "104 St", imgName: ["/last_stop/Queens/104_street_oxford_avenue_a.jpg", "/last_stop/Queens/104_street_oxford_avenue_a-2.jpg"]},
    { loc: "2385,2439,16", name: "Aqueduct Racetrack", imgName: ["/last_stop/Queens/aqueduct_racetrack_a.jpg"]},
    { loc: "2384,2479,16", name: "Aqueduct/ North Conduit Av", imgName: ["/last_stop/Queens/aqueduct_north_contuit_avenue_a.jpg", "/last_stop/Queens/aqueduct_north_contuit_avenue_a-2.jpg"]},
    { loc: "2406,2550,16", name: "Howard Beach/ JFK Airport", imgName: ["/last_stop/Queens/Howard_Beach_JFK-1.jpg"]},
    { loc: "2513,2872,16", name: "Broad Channel", imgName: ["/last_stop/Queens/Broad_Channel-1.jpg"]},
    { loc: "2621,2923,16", name: "Beach 67 St", imgName: ["/last_stop/Queens/Beach_67_Arverne_By_The_Sea_A-1.jpg", "/last_stop/Queens/Beach_67_Arverne_By_The_Sea_A-2.jpg"]},
    { loc: "2643,2888,16", name: "Beach 60 St", imgName: ["/last_stop/Queens/Beach_60_Straiton_A-2.jpg", "/last_stop/Queens/Beach_60_Straiton_A-1.jpg"]},
    { loc: "2664,2863,16", name: "Beach 44 St", imgName: ["/last_stop/Queens/Beach_44_Frank_Ave_A-1.jpg", "/last_stop/Queens/Beach_44_Frank_Ave_A-2.jpg"]},
    { loc: "2690,2832,16", name: "Beach 36 St", imgName: ["/last_stop/Queens/Beach_36_Edgemere_A-1.jpg", "/last_stop/Queens/Beach_36_Edgemere_A-2.jpg"]},
    { loc: "2690,2797,16", name: "Beach 25 St", imgName: ["/last_stop/Queens/Beach_25_Wavecrest-1.jpg", "/last_stop/Queens/Beach_25_Wavecrest-2.jpg"]},
    { loc: "2703,2764,16", name: "Far Rockaway/ Mott Av", imgName: ["/last_stop/Queens/Far_Rockaway_Mott_Avenue-1.jpg"]},
    { loc: "2561,3017,16", name: "Beach 90 St", imgName: ["/last_stop/Queens/Beach_90_Holland_A_S-2.jpg", "/last_stop/Queens/Beach_90_Holland_A_S-1.jpg"]},
    { loc: "2553,3061,16", name: "Beach 98 St", imgName: ["/last_stop/Queens/Beach_98_Playland_A_S-1.jpg"]},
    { loc: "2529,3107,16", name: "Beach 105 St", imgName: ["/last_stop/Queens/beach_105_seaside_a_s.jpg", "/last_stop/Queens/beach_105_seaside_a_s-2.jpg"]},
    { loc: "2505,3146,16", name: "Rockaway Park/ Beach 116 St", imgName: ["/last_stop/Queens/rockaway_park_beach_116_street_a_s-1.jpg"]},
    { loc: "2287,2346,16", name: "Rockaway Blvd", imgName: ["/last_stop/Queens/rockaway_boulevard_a.jpg"]},
    { loc: "2260,2367,16", name: "88 St", imgName: ["/last_stop/Queens/88_street_boyd_avenue_a-2.jpg", "/last_stop/Queens/88_street_boyd_avenue_a.jpg"]},
    { loc: "2234,2397,16", name: "80 St", imgName: ["/last_stop/Queens/80_street_hudson_street_a.jpg"]},
    { loc: "1778,2372,16", name: "Seneca Av", imgName: ["/last_stop/Queens/seneca_avenue_m-2.jpg", "/last_stop/Queens/seneca_avenue_m-3.jpg"]},
    { loc: "1785,2337,16", name: "Forest Av", imgName: ["/last_stop/Queens/forest_avenue_m-2.jpg", "/last_stop/Queens/forest_avenue_m.jpg"]},
    { loc: "1787,2305,16", name: "Fresh Pond Rd", imgName: ["/last_stop/Queens/fresh_pond_road_m.jpg", "/last_stop/Queens/fresh_pond_road_m-2.jpg"]},
    { loc: "1787,2268,16", name: "Middle Village/ Metropolitan Av", imgName: ["/last_stop/Queens/metropolitan_avenue_m.jpg"]},
    { loc: "1271,2095,16", name: "36 St", imgName: ["/last_stop/Queens/36_street_m_r-2.jpg", "/last_stop/Queens/36_street_m_r.jpg"]}
];